const defaultMap = {
    "b": "https://github.com/issues/assigned",
    "b-q": null,
    "c": "https://calendar.google.com",
    "c-q": "/calendar/embed?src=%s%40gmail.com",
    "cl": "https://github.com/pulls",
    "cl-q": null,
    "cs": "https://github.com/search",
    "cs-q": "?type=code&q=",
    "docs": "https://docs.google.com",
    "docs-q": "/document/u/0/?q=",
    "drive": "https://drive.google.com",
    "drive-q": "/drive/search?q=",
    "m": "https://mail.google.com/",
    "m-q": "/mail/#search/",
    "moma": "https://www.google.com",
    "moma-q": "/search?q=",
    "sheets": "https://docs.google.com/spreadsheets",
    "sheets-q": "?q=",
    "slides": "https://docs.google.com/presentation",
    "slides-q": "?q=",
    "who": "https://www.linkedin.com/",
    "who-q": "/search/results/all/?keywords="
}
